name: 构建镜像
on: 
  push:
    tags: ['v*.*.*']

jobs:
  image-push:
    name: 环境
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库
        uses: actions/checkout@v4

      - name: 登录docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_NAME}}
          password: ${{secrets.DOCKER_TOKEN}}


      - name: 获取tag
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{secrets.DOCKER_NAME}}/backend


      - name: 构建镜像&&推送
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{steps.meta.outputs.tags}}
